// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package http

import (
	"fmt"
	"math/bits"
	"net/http"
	"sync/atomic"

	"moqueries.org/runtime/moq"
)

// The following type assertion assures that http.Flusher is mocked completely
var _ http.Flusher = (*MoqFlusher_mock)(nil)

// MoqFlusher holds the state of a moq of the Flusher type
type MoqFlusher struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqFlusher_mock

	ResultsByParams_Flush []MoqFlusher_Flush_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			Flush struct{}
		}
	}
}

// MoqFlusher_mock isolates the mock interface of the Flusher type
type MoqFlusher_mock struct {
	Moq *MoqFlusher
}

// MoqFlusher_recorder isolates the recorder interface of the Flusher type
type MoqFlusher_recorder struct {
	Moq *MoqFlusher
}

// MoqFlusher_Flush_params holds the params of the Flusher type
type MoqFlusher_Flush_params struct{}

// MoqFlusher_Flush_paramsKey holds the map key params of the Flusher type
type MoqFlusher_Flush_paramsKey struct {
	Params struct{}
	Hashes struct{}
}

// MoqFlusher_Flush_resultsByParams contains the results for a given set of
// parameters for the Flusher type
type MoqFlusher_Flush_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqFlusher_Flush_paramsKey]*MoqFlusher_Flush_results
}

// MoqFlusher_Flush_doFn defines the type of function needed when calling AndDo
// for the Flusher type
type MoqFlusher_Flush_doFn func()

// MoqFlusher_Flush_doReturnFn defines the type of function needed when calling
// DoReturnResults for the Flusher type
type MoqFlusher_Flush_doReturnFn func()

// MoqFlusher_Flush_results holds the results of the Flusher type
type MoqFlusher_Flush_results struct {
	Params  MoqFlusher_Flush_params
	Results []struct {
		Values     *struct{}
		Sequence   uint32
		DoFn       MoqFlusher_Flush_doFn
		DoReturnFn MoqFlusher_Flush_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqFlusher_Flush_fnRecorder routes recorded function calls to the MoqFlusher
// moq
type MoqFlusher_Flush_fnRecorder struct {
	Params    MoqFlusher_Flush_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqFlusher_Flush_results
	Moq       *MoqFlusher
}

// MoqFlusher_Flush_anyParams isolates the any params functions of the Flusher
// type
type MoqFlusher_Flush_anyParams struct {
	Recorder *MoqFlusher_Flush_fnRecorder
}

// NewMoqFlusher creates a new moq of the Flusher type
func NewMoqFlusher(scene *moq.Scene, config *moq.Config) *MoqFlusher {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqFlusher{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqFlusher_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				Flush struct{}
			}
		}{ParameterIndexing: struct {
			Flush struct{}
		}{
			Flush: struct{}{},
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the mock implementation of the Flusher type
func (m *MoqFlusher) Mock() *MoqFlusher_mock { return m.Moq }

func (m *MoqFlusher_mock) Flush() {
	m.Moq.Scene.T.Helper()
	params := MoqFlusher_Flush_params{}
	var results *MoqFlusher_Flush_results
	for _, resultsByParams := range m.Moq.ResultsByParams_Flush {
		paramsKey := m.Moq.ParamsKey_Flush(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams_Flush(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams_Flush(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams_Flush(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn()
	}

	if result.DoReturnFn != nil {
		result.DoReturnFn()
	}
	return
}

// OnCall returns the recorder implementation of the Flusher type
func (m *MoqFlusher) OnCall() *MoqFlusher_recorder {
	return &MoqFlusher_recorder{
		Moq: m,
	}
}

func (m *MoqFlusher_recorder) Flush() *MoqFlusher_Flush_fnRecorder {
	return &MoqFlusher_Flush_fnRecorder{
		Params:   MoqFlusher_Flush_params{},
		Sequence: m.Moq.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m.Moq,
	}
}

func (r *MoqFlusher_Flush_fnRecorder) Any() *MoqFlusher_Flush_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Flush(r.Params))
		return nil
	}
	return &MoqFlusher_Flush_anyParams{Recorder: r}
}

func (r *MoqFlusher_Flush_fnRecorder) Seq() *MoqFlusher_Flush_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Flush(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqFlusher_Flush_fnRecorder) NoSeq() *MoqFlusher_Flush_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Flush(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqFlusher_Flush_fnRecorder) ReturnResults() *MoqFlusher_Flush_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values     *struct{}
		Sequence   uint32
		DoFn       MoqFlusher_Flush_doFn
		DoReturnFn MoqFlusher_Flush_doReturnFn
	}{
		Values:   &struct{}{},
		Sequence: sequence,
	})
	return r
}

func (r *MoqFlusher_Flush_fnRecorder) AndDo(fn MoqFlusher_Flush_doFn) *MoqFlusher_Flush_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqFlusher_Flush_fnRecorder) DoReturnResults(fn MoqFlusher_Flush_doReturnFn) *MoqFlusher_Flush_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values     *struct{}
		Sequence   uint32
		DoFn       MoqFlusher_Flush_doFn
		DoReturnFn MoqFlusher_Flush_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqFlusher_Flush_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqFlusher_Flush_resultsByParams
	for n, res := range r.Moq.ResultsByParams_Flush {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqFlusher_Flush_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqFlusher_Flush_paramsKey]*MoqFlusher_Flush_results{},
		}
		r.Moq.ResultsByParams_Flush = append(r.Moq.ResultsByParams_Flush, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams_Flush) {
			copy(r.Moq.ResultsByParams_Flush[insertAt+1:], r.Moq.ResultsByParams_Flush[insertAt:0])
			r.Moq.ResultsByParams_Flush[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey_Flush(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqFlusher_Flush_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqFlusher_Flush_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqFlusher_Flush_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values     *struct{}
				Sequence   uint32
				DoFn       MoqFlusher_Flush_doFn
				DoReturnFn MoqFlusher_Flush_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqFlusher) PrettyParams_Flush(params MoqFlusher_Flush_params) string {
	return fmt.Sprintf("Flush()")
}

func (m *MoqFlusher) ParamsKey_Flush(params MoqFlusher_Flush_params, anyParams uint64) MoqFlusher_Flush_paramsKey {
	m.Scene.T.Helper()
	return MoqFlusher_Flush_paramsKey{
		Params: struct{}{},
		Hashes: struct{}{},
	}
}

// Reset resets the state of the moq
func (m *MoqFlusher) Reset() { m.ResultsByParams_Flush = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqFlusher) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams_Flush {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams_Flush(results.Params))
			}
		}
	}
}
