// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package ecdsa

import (
	"crypto"
	"fmt"
	"math/bits"
	"sync/atomic"

	"moqueries.org/runtime/hash"
	"moqueries.org/runtime/moq"
)

// The following type assertion assures that ecdsa.PublicKey_starGenType is
// mocked completely
var _ PublicKey_starGenType = (*MoqPublicKey_starGenType_mock)(nil)

// PublicKey_starGenType is the fabricated implementation type of this mock
// (emitted when mocking a collections of methods directly and not from an
// interface type)
type PublicKey_starGenType interface {
	Equal(x crypto.PublicKey) bool
}

// MoqPublicKey_starGenType holds the state of a moq of the
// PublicKey_starGenType type
type MoqPublicKey_starGenType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqPublicKey_starGenType_mock

	ResultsByParams_Equal []MoqPublicKey_starGenType_Equal_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			Equal struct {
				X moq.ParamIndexing
			}
		}
	}
	// MoqPublicKey_starGenType_mock isolates the mock interface of the
}

// PublicKey_starGenType type
type MoqPublicKey_starGenType_mock struct {
	Moq *MoqPublicKey_starGenType
}

// MoqPublicKey_starGenType_recorder isolates the recorder interface of the
// PublicKey_starGenType type
type MoqPublicKey_starGenType_recorder struct {
	Moq *MoqPublicKey_starGenType
}

// MoqPublicKey_starGenType_Equal_params holds the params of the
// PublicKey_starGenType type
type MoqPublicKey_starGenType_Equal_params struct{ X crypto.PublicKey }

// MoqPublicKey_starGenType_Equal_paramsKey holds the map key params of the
// PublicKey_starGenType type
type MoqPublicKey_starGenType_Equal_paramsKey struct {
	Params struct{ X crypto.PublicKey }
	Hashes struct{ X hash.Hash }
}

// MoqPublicKey_starGenType_Equal_resultsByParams contains the results for a
// given set of parameters for the PublicKey_starGenType type
type MoqPublicKey_starGenType_Equal_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqPublicKey_starGenType_Equal_paramsKey]*MoqPublicKey_starGenType_Equal_results
}

// MoqPublicKey_starGenType_Equal_doFn defines the type of function needed when
// calling AndDo for the PublicKey_starGenType type
type MoqPublicKey_starGenType_Equal_doFn func(x crypto.PublicKey)

// MoqPublicKey_starGenType_Equal_doReturnFn defines the type of function
// needed when calling DoReturnResults for the PublicKey_starGenType type
type MoqPublicKey_starGenType_Equal_doReturnFn func(x crypto.PublicKey) bool

// MoqPublicKey_starGenType_Equal_results holds the results of the
// PublicKey_starGenType type
type MoqPublicKey_starGenType_Equal_results struct {
	Params  MoqPublicKey_starGenType_Equal_params
	Results []struct {
		Values *struct {
			Result1 bool
		}
		Sequence   uint32
		DoFn       MoqPublicKey_starGenType_Equal_doFn
		DoReturnFn MoqPublicKey_starGenType_Equal_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqPublicKey_starGenType_Equal_fnRecorder routes recorded function calls to
// the MoqPublicKey_starGenType moq
type MoqPublicKey_starGenType_Equal_fnRecorder struct {
	Params    MoqPublicKey_starGenType_Equal_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqPublicKey_starGenType_Equal_results
	Moq       *MoqPublicKey_starGenType
}

// MoqPublicKey_starGenType_Equal_anyParams isolates the any params functions
// of the PublicKey_starGenType type
type MoqPublicKey_starGenType_Equal_anyParams struct {
	Recorder *MoqPublicKey_starGenType_Equal_fnRecorder
}

// NewMoqPublicKey_starGenType creates a new moq of the PublicKey_starGenType
// type
func NewMoqPublicKey_starGenType(scene *moq.Scene, config *moq.Config) *MoqPublicKey_starGenType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqPublicKey_starGenType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqPublicKey_starGenType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				Equal struct {
					X moq.ParamIndexing
				}
			}
		}{ParameterIndexing: struct {
			Equal struct {
				X moq.ParamIndexing
			}
		}{
			Equal: struct {
				X moq.ParamIndexing
			}{
				X: moq.ParamIndexByValue,
			},
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the mock implementation of the PublicKey_starGenType type
func (m *MoqPublicKey_starGenType) Mock() *MoqPublicKey_starGenType_mock { return m.Moq }

func (m *MoqPublicKey_starGenType_mock) Equal(x crypto.PublicKey) (result1 bool) {
	m.Moq.Scene.T.Helper()
	params := MoqPublicKey_starGenType_Equal_params{
		X: x,
	}
	var results *MoqPublicKey_starGenType_Equal_results
	for _, resultsByParams := range m.Moq.ResultsByParams_Equal {
		paramsKey := m.Moq.ParamsKey_Equal(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams_Equal(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams_Equal(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams_Equal(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn(x)
	}

	if result.Values != nil {
		result1 = result.Values.Result1
	}
	if result.DoReturnFn != nil {
		result1 = result.DoReturnFn(x)
	}
	return
}

// OnCall returns the recorder implementation of the PublicKey_starGenType type
func (m *MoqPublicKey_starGenType) OnCall() *MoqPublicKey_starGenType_recorder {
	return &MoqPublicKey_starGenType_recorder{
		Moq: m,
	}
}

func (m *MoqPublicKey_starGenType_recorder) Equal(x crypto.PublicKey) *MoqPublicKey_starGenType_Equal_fnRecorder {
	return &MoqPublicKey_starGenType_Equal_fnRecorder{
		Params: MoqPublicKey_starGenType_Equal_params{
			X: x,
		},
		Sequence: m.Moq.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m.Moq,
	}
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) Any() *MoqPublicKey_starGenType_Equal_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Equal(r.Params))
		return nil
	}
	return &MoqPublicKey_starGenType_Equal_anyParams{Recorder: r}
}

func (a *MoqPublicKey_starGenType_Equal_anyParams) X() *MoqPublicKey_starGenType_Equal_fnRecorder {
	a.Recorder.AnyParams |= 1 << 0
	return a.Recorder
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) Seq() *MoqPublicKey_starGenType_Equal_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Equal(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) NoSeq() *MoqPublicKey_starGenType_Equal_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Equal(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) ReturnResults(result1 bool) *MoqPublicKey_starGenType_Equal_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 bool
		}
		Sequence   uint32
		DoFn       MoqPublicKey_starGenType_Equal_doFn
		DoReturnFn MoqPublicKey_starGenType_Equal_doReturnFn
	}{
		Values: &struct {
			Result1 bool
		}{
			Result1: result1,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) AndDo(fn MoqPublicKey_starGenType_Equal_doFn) *MoqPublicKey_starGenType_Equal_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) DoReturnResults(fn MoqPublicKey_starGenType_Equal_doReturnFn) *MoqPublicKey_starGenType_Equal_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 bool
		}
		Sequence   uint32
		DoFn       MoqPublicKey_starGenType_Equal_doFn
		DoReturnFn MoqPublicKey_starGenType_Equal_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqPublicKey_starGenType_Equal_resultsByParams
	for n, res := range r.Moq.ResultsByParams_Equal {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqPublicKey_starGenType_Equal_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqPublicKey_starGenType_Equal_paramsKey]*MoqPublicKey_starGenType_Equal_results{},
		}
		r.Moq.ResultsByParams_Equal = append(r.Moq.ResultsByParams_Equal, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams_Equal) {
			copy(r.Moq.ResultsByParams_Equal[insertAt+1:], r.Moq.ResultsByParams_Equal[insertAt:0])
			r.Moq.ResultsByParams_Equal[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey_Equal(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqPublicKey_starGenType_Equal_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqPublicKey_starGenType_Equal_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqPublicKey_starGenType_Equal_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 bool
				}
				Sequence   uint32
				DoFn       MoqPublicKey_starGenType_Equal_doFn
				DoReturnFn MoqPublicKey_starGenType_Equal_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqPublicKey_starGenType) PrettyParams_Equal(params MoqPublicKey_starGenType_Equal_params) string {
	return fmt.Sprintf("Equal(%#v)", params.X)
}

func (m *MoqPublicKey_starGenType) ParamsKey_Equal(params MoqPublicKey_starGenType_Equal_params, anyParams uint64) MoqPublicKey_starGenType_Equal_paramsKey {
	m.Scene.T.Helper()
	var xUsed crypto.PublicKey
	var xUsedHash hash.Hash
	if anyParams&(1<<0) == 0 {
		if m.Runtime.ParameterIndexing.Equal.X == moq.ParamIndexByValue {
			xUsed = params.X
		} else {
			xUsedHash = hash.DeepHash(params.X)
		}
	}
	return MoqPublicKey_starGenType_Equal_paramsKey{
		Params: struct{ X crypto.PublicKey }{
			X: xUsed,
		},
		Hashes: struct{ X hash.Hash }{
			X: xUsedHash,
		},
	}
}

// Reset resets the state of the moq
func (m *MoqPublicKey_starGenType) Reset() { m.ResultsByParams_Equal = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqPublicKey_starGenType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams_Equal {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams_Equal(results.Params))
			}
		}
	}
}
