// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package parse

import (
	"fmt"
	"math/bits"
	"sync/atomic"
	"text/template/parse"

	"moqueries.org/runtime/moq"
)

// The following type assertion assures that parse.BranchNode_starGenType is
// mocked completely
var _ BranchNode_starGenType = (*MoqBranchNode_starGenType_mock)(nil)

// BranchNode_starGenType is the fabricated implementation type of this mock
// (emitted when mocking a collections of methods directly and not from an
// interface type)
type BranchNode_starGenType interface {
	String() string
	Copy() parse.Node
}

// MoqBranchNode_starGenType holds the state of a moq of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqBranchNode_starGenType_mock

	ResultsByParams_String []MoqBranchNode_starGenType_String_resultsByParams
	ResultsByParams_Copy   []MoqBranchNode_starGenType_Copy_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			String struct{}
			Copy   struct{}
		}
	}
}

// MoqBranchNode_starGenType_mock isolates the mock interface of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_mock struct {
	Moq *MoqBranchNode_starGenType
}

// MoqBranchNode_starGenType_recorder isolates the recorder interface of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_recorder struct {
	Moq *MoqBranchNode_starGenType
}

// MoqBranchNode_starGenType_String_params holds the params of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_String_params struct{}

// MoqBranchNode_starGenType_String_paramsKey holds the map key params of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_String_paramsKey struct {
	Params struct{}
	Hashes struct{}
}

// MoqBranchNode_starGenType_String_resultsByParams contains the results for a
// given set of parameters for the BranchNode_starGenType type
type MoqBranchNode_starGenType_String_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqBranchNode_starGenType_String_paramsKey]*MoqBranchNode_starGenType_String_results
}

// MoqBranchNode_starGenType_String_doFn defines the type of function needed
// when calling AndDo for the BranchNode_starGenType type
type MoqBranchNode_starGenType_String_doFn func()

// MoqBranchNode_starGenType_String_doReturnFn defines the type of function
// needed when calling DoReturnResults for the BranchNode_starGenType type
type MoqBranchNode_starGenType_String_doReturnFn func() string

// MoqBranchNode_starGenType_String_results holds the results of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_String_results struct {
	Params  MoqBranchNode_starGenType_String_params
	Results []struct {
		Values *struct {
			Result1 string
		}
		Sequence   uint32
		DoFn       MoqBranchNode_starGenType_String_doFn
		DoReturnFn MoqBranchNode_starGenType_String_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqBranchNode_starGenType_String_fnRecorder routes recorded function calls
// to the MoqBranchNode_starGenType moq
type MoqBranchNode_starGenType_String_fnRecorder struct {
	Params    MoqBranchNode_starGenType_String_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqBranchNode_starGenType_String_results
	Moq       *MoqBranchNode_starGenType
}

// MoqBranchNode_starGenType_String_anyParams isolates the any params functions
// of the BranchNode_starGenType type
type MoqBranchNode_starGenType_String_anyParams struct {
	Recorder *MoqBranchNode_starGenType_String_fnRecorder
}

// MoqBranchNode_starGenType_Copy_params holds the params of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_Copy_params struct{}

// MoqBranchNode_starGenType_Copy_paramsKey holds the map key params of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_Copy_paramsKey struct {
	Params struct{}
	Hashes struct{}
}

// MoqBranchNode_starGenType_Copy_resultsByParams contains the results for a
// given set of parameters for the BranchNode_starGenType type
type MoqBranchNode_starGenType_Copy_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqBranchNode_starGenType_Copy_paramsKey]*MoqBranchNode_starGenType_Copy_results
}

// MoqBranchNode_starGenType_Copy_doFn defines the type of function needed when
// calling AndDo for the BranchNode_starGenType type
type MoqBranchNode_starGenType_Copy_doFn func()

// MoqBranchNode_starGenType_Copy_doReturnFn defines the type of function
// needed when calling DoReturnResults for the BranchNode_starGenType type
type MoqBranchNode_starGenType_Copy_doReturnFn func() parse.Node

// MoqBranchNode_starGenType_Copy_results holds the results of the
// BranchNode_starGenType type
type MoqBranchNode_starGenType_Copy_results struct {
	Params  MoqBranchNode_starGenType_Copy_params
	Results []struct {
		Values *struct {
			Result1 parse.Node
		}
		Sequence   uint32
		DoFn       MoqBranchNode_starGenType_Copy_doFn
		DoReturnFn MoqBranchNode_starGenType_Copy_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqBranchNode_starGenType_Copy_fnRecorder routes recorded function calls to
// the MoqBranchNode_starGenType moq
type MoqBranchNode_starGenType_Copy_fnRecorder struct {
	Params    MoqBranchNode_starGenType_Copy_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqBranchNode_starGenType_Copy_results
	Moq       *MoqBranchNode_starGenType
}

// MoqBranchNode_starGenType_Copy_anyParams isolates the any params functions
// of the BranchNode_starGenType type
type MoqBranchNode_starGenType_Copy_anyParams struct {
	Recorder *MoqBranchNode_starGenType_Copy_fnRecorder
}

// NewMoqBranchNode_starGenType creates a new moq of the BranchNode_starGenType
// type
func NewMoqBranchNode_starGenType(scene *moq.Scene, config *moq.Config) *MoqBranchNode_starGenType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqBranchNode_starGenType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqBranchNode_starGenType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				String struct{}
				Copy   struct{}
			}
		}{ParameterIndexing: struct {
			String struct{}
			Copy   struct{}
		}{
			String: struct{}{},
			Copy:   struct{}{},
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the mock implementation of the BranchNode_starGenType type
func (m *MoqBranchNode_starGenType) Mock() *MoqBranchNode_starGenType_mock { return m.Moq }

func (m *MoqBranchNode_starGenType_mock) String() (result1 string) {
	m.Moq.Scene.T.Helper()
	params := MoqBranchNode_starGenType_String_params{}
	var results *MoqBranchNode_starGenType_String_results
	for _, resultsByParams := range m.Moq.ResultsByParams_String {
		paramsKey := m.Moq.ParamsKey_String(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams_String(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams_String(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams_String(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn()
	}

	if result.Values != nil {
		result1 = result.Values.Result1
	}
	if result.DoReturnFn != nil {
		result1 = result.DoReturnFn()
	}
	return
}

func (m *MoqBranchNode_starGenType_mock) Copy() (result1 parse.Node) {
	m.Moq.Scene.T.Helper()
	params := MoqBranchNode_starGenType_Copy_params{}
	var results *MoqBranchNode_starGenType_Copy_results
	for _, resultsByParams := range m.Moq.ResultsByParams_Copy {
		paramsKey := m.Moq.ParamsKey_Copy(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams_Copy(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams_Copy(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams_Copy(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn()
	}

	if result.Values != nil {
		result1 = result.Values.Result1
	}
	if result.DoReturnFn != nil {
		result1 = result.DoReturnFn()
	}
	return
}

// OnCall returns the recorder implementation of the BranchNode_starGenType
// type
func (m *MoqBranchNode_starGenType) OnCall() *MoqBranchNode_starGenType_recorder {
	return &MoqBranchNode_starGenType_recorder{
		Moq: m,
	}
}

func (m *MoqBranchNode_starGenType_recorder) String() *MoqBranchNode_starGenType_String_fnRecorder {
	return &MoqBranchNode_starGenType_String_fnRecorder{
		Params:   MoqBranchNode_starGenType_String_params{},
		Sequence: m.Moq.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m.Moq,
	}
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) Any() *MoqBranchNode_starGenType_String_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_String(r.Params))
		return nil
	}
	return &MoqBranchNode_starGenType_String_anyParams{Recorder: r}
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) Seq() *MoqBranchNode_starGenType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_String(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) NoSeq() *MoqBranchNode_starGenType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_String(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) ReturnResults(result1 string) *MoqBranchNode_starGenType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 string
		}
		Sequence   uint32
		DoFn       MoqBranchNode_starGenType_String_doFn
		DoReturnFn MoqBranchNode_starGenType_String_doReturnFn
	}{
		Values: &struct {
			Result1 string
		}{
			Result1: result1,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) AndDo(fn MoqBranchNode_starGenType_String_doFn) *MoqBranchNode_starGenType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) DoReturnResults(fn MoqBranchNode_starGenType_String_doReturnFn) *MoqBranchNode_starGenType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 string
		}
		Sequence   uint32
		DoFn       MoqBranchNode_starGenType_String_doFn
		DoReturnFn MoqBranchNode_starGenType_String_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqBranchNode_starGenType_String_resultsByParams
	for n, res := range r.Moq.ResultsByParams_String {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqBranchNode_starGenType_String_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqBranchNode_starGenType_String_paramsKey]*MoqBranchNode_starGenType_String_results{},
		}
		r.Moq.ResultsByParams_String = append(r.Moq.ResultsByParams_String, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams_String) {
			copy(r.Moq.ResultsByParams_String[insertAt+1:], r.Moq.ResultsByParams_String[insertAt:0])
			r.Moq.ResultsByParams_String[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey_String(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqBranchNode_starGenType_String_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqBranchNode_starGenType_String_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqBranchNode_starGenType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 string
				}
				Sequence   uint32
				DoFn       MoqBranchNode_starGenType_String_doFn
				DoReturnFn MoqBranchNode_starGenType_String_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqBranchNode_starGenType) PrettyParams_String(params MoqBranchNode_starGenType_String_params) string {
	return fmt.Sprintf("String()")
}

func (m *MoqBranchNode_starGenType) ParamsKey_String(params MoqBranchNode_starGenType_String_params, anyParams uint64) MoqBranchNode_starGenType_String_paramsKey {
	m.Scene.T.Helper()
	return MoqBranchNode_starGenType_String_paramsKey{
		Params: struct{}{},
		Hashes: struct{}{},
	}
}

func (m *MoqBranchNode_starGenType_recorder) Copy() *MoqBranchNode_starGenType_Copy_fnRecorder {
	return &MoqBranchNode_starGenType_Copy_fnRecorder{
		Params:   MoqBranchNode_starGenType_Copy_params{},
		Sequence: m.Moq.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m.Moq,
	}
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) Any() *MoqBranchNode_starGenType_Copy_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Copy(r.Params))
		return nil
	}
	return &MoqBranchNode_starGenType_Copy_anyParams{Recorder: r}
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) Seq() *MoqBranchNode_starGenType_Copy_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Copy(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) NoSeq() *MoqBranchNode_starGenType_Copy_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_Copy(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) ReturnResults(result1 parse.Node) *MoqBranchNode_starGenType_Copy_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 parse.Node
		}
		Sequence   uint32
		DoFn       MoqBranchNode_starGenType_Copy_doFn
		DoReturnFn MoqBranchNode_starGenType_Copy_doReturnFn
	}{
		Values: &struct {
			Result1 parse.Node
		}{
			Result1: result1,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) AndDo(fn MoqBranchNode_starGenType_Copy_doFn) *MoqBranchNode_starGenType_Copy_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) DoReturnResults(fn MoqBranchNode_starGenType_Copy_doReturnFn) *MoqBranchNode_starGenType_Copy_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 parse.Node
		}
		Sequence   uint32
		DoFn       MoqBranchNode_starGenType_Copy_doFn
		DoReturnFn MoqBranchNode_starGenType_Copy_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqBranchNode_starGenType_Copy_resultsByParams
	for n, res := range r.Moq.ResultsByParams_Copy {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqBranchNode_starGenType_Copy_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqBranchNode_starGenType_Copy_paramsKey]*MoqBranchNode_starGenType_Copy_results{},
		}
		r.Moq.ResultsByParams_Copy = append(r.Moq.ResultsByParams_Copy, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams_Copy) {
			copy(r.Moq.ResultsByParams_Copy[insertAt+1:], r.Moq.ResultsByParams_Copy[insertAt:0])
			r.Moq.ResultsByParams_Copy[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey_Copy(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqBranchNode_starGenType_Copy_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqBranchNode_starGenType_Copy_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqBranchNode_starGenType_Copy_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 parse.Node
				}
				Sequence   uint32
				DoFn       MoqBranchNode_starGenType_Copy_doFn
				DoReturnFn MoqBranchNode_starGenType_Copy_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqBranchNode_starGenType) PrettyParams_Copy(params MoqBranchNode_starGenType_Copy_params) string {
	return fmt.Sprintf("Copy()")
}

func (m *MoqBranchNode_starGenType) ParamsKey_Copy(params MoqBranchNode_starGenType_Copy_params, anyParams uint64) MoqBranchNode_starGenType_Copy_paramsKey {
	m.Scene.T.Helper()
	return MoqBranchNode_starGenType_Copy_paramsKey{
		Params: struct{}{},
		Hashes: struct{}{},
	}
}

// Reset resets the state of the moq
func (m *MoqBranchNode_starGenType) Reset() {
	m.ResultsByParams_String = nil
	m.ResultsByParams_Copy = nil
}

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqBranchNode_starGenType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams_String {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams_String(results.Params))
			}
		}
	}
	for _, res := range m.ResultsByParams_Copy {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams_Copy(results.Params))
			}
		}
	}
}
