// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package parse

import (
	"fmt"
	"math/bits"
	"sync/atomic"
	"text/template/parse"

	"moqueries.org/runtime/hash"
	"moqueries.org/runtime/moq"
)

// Parse_genType is the fabricated implementation type of this mock (emitted
// when mocking functions directly and not from a function type)
type Parse_genType func(name, text, leftDelim, rightDelim string, funcs ...map[string]interface{}) (map[string]*parse.Tree, error)

// MoqParse_genType holds the state of a moq of the Parse_genType type
type MoqParse_genType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqParse_genType_mock

	ResultsByParams []MoqParse_genType_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			Name       moq.ParamIndexing
			Text       moq.ParamIndexing
			LeftDelim  moq.ParamIndexing
			RightDelim moq.ParamIndexing
			Funcs      moq.ParamIndexing
		}
	}
}

// MoqParse_genType_mock isolates the mock interface of the Parse_genType type
type MoqParse_genType_mock struct {
	Moq *MoqParse_genType
}

// MoqParse_genType_params holds the params of the Parse_genType type
type MoqParse_genType_params struct {
	Name, Text, LeftDelim, RightDelim string
	Funcs                             []map[string]interface{}
}

// MoqParse_genType_paramsKey holds the map key params of the Parse_genType
// type
type MoqParse_genType_paramsKey struct {
	Params struct{ Name, Text, LeftDelim, RightDelim string }
	Hashes struct {
		Name, Text, LeftDelim, RightDelim hash.Hash
		Funcs                             hash.Hash
	}
}

// MoqParse_genType_resultsByParams contains the results for a given set of
// parameters for the Parse_genType type
type MoqParse_genType_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqParse_genType_paramsKey]*MoqParse_genType_results
}

// MoqParse_genType_doFn defines the type of function needed when calling AndDo
// for the Parse_genType type
type MoqParse_genType_doFn func(name, text, leftDelim, rightDelim string, funcs ...map[string]interface{})

// MoqParse_genType_doReturnFn defines the type of function needed when calling
// DoReturnResults for the Parse_genType type
type MoqParse_genType_doReturnFn func(name, text, leftDelim, rightDelim string, funcs ...map[string]interface{}) (map[string]*parse.Tree, error)

// MoqParse_genType_results holds the results of the Parse_genType type
type MoqParse_genType_results struct {
	Params  MoqParse_genType_params
	Results []struct {
		Values *struct {
			Result1 map[string]*parse.Tree
			Result2 error
		}
		Sequence   uint32
		DoFn       MoqParse_genType_doFn
		DoReturnFn MoqParse_genType_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqParse_genType_fnRecorder routes recorded function calls to the
// MoqParse_genType moq
type MoqParse_genType_fnRecorder struct {
	Params    MoqParse_genType_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqParse_genType_results
	Moq       *MoqParse_genType
}

// MoqParse_genType_anyParams isolates the any params functions of the
// Parse_genType type
type MoqParse_genType_anyParams struct {
	Recorder *MoqParse_genType_fnRecorder
}

// NewMoqParse_genType creates a new moq of the Parse_genType type
func NewMoqParse_genType(scene *moq.Scene, config *moq.Config) *MoqParse_genType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqParse_genType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqParse_genType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				Name       moq.ParamIndexing
				Text       moq.ParamIndexing
				LeftDelim  moq.ParamIndexing
				RightDelim moq.ParamIndexing
				Funcs      moq.ParamIndexing
			}
		}{ParameterIndexing: struct {
			Name       moq.ParamIndexing
			Text       moq.ParamIndexing
			LeftDelim  moq.ParamIndexing
			RightDelim moq.ParamIndexing
			Funcs      moq.ParamIndexing
		}{
			Name:       moq.ParamIndexByValue,
			Text:       moq.ParamIndexByValue,
			LeftDelim:  moq.ParamIndexByValue,
			RightDelim: moq.ParamIndexByValue,
			Funcs:      moq.ParamIndexByHash,
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the moq implementation of the Parse_genType type
func (m *MoqParse_genType) Mock() Parse_genType {
	return func(name, text, leftDelim, rightDelim string, funcs ...map[string]interface{}) (map[string]*parse.Tree, error) {
		m.Scene.T.Helper()
		moq := &MoqParse_genType_mock{Moq: m}
		return moq.Fn(name, text, leftDelim, rightDelim, funcs...)
	}
}

func (m *MoqParse_genType_mock) Fn(name, text, leftDelim, rightDelim string, funcs ...map[string]interface{}) (result1 map[string]*parse.Tree, result2 error) {
	m.Moq.Scene.T.Helper()
	params := MoqParse_genType_params{
		Name:       name,
		Text:       text,
		LeftDelim:  leftDelim,
		RightDelim: rightDelim,
		Funcs:      funcs,
	}
	var results *MoqParse_genType_results
	for _, resultsByParams := range m.Moq.ResultsByParams {
		paramsKey := m.Moq.ParamsKey(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn(name, text, leftDelim, rightDelim, funcs...)
	}

	if result.Values != nil {
		result1 = result.Values.Result1
		result2 = result.Values.Result2
	}
	if result.DoReturnFn != nil {
		result1, result2 = result.DoReturnFn(name, text, leftDelim, rightDelim, funcs...)
	}
	return
}

func (m *MoqParse_genType) OnCall(name, text, leftDelim, rightDelim string, funcs ...map[string]interface{}) *MoqParse_genType_fnRecorder {
	return &MoqParse_genType_fnRecorder{
		Params: MoqParse_genType_params{
			Name:       name,
			Text:       text,
			LeftDelim:  leftDelim,
			RightDelim: rightDelim,
			Funcs:      funcs,
		},
		Sequence: m.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m,
	}
}

func (r *MoqParse_genType_fnRecorder) Any() *MoqParse_genType_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	return &MoqParse_genType_anyParams{Recorder: r}
}

func (a *MoqParse_genType_anyParams) Name() *MoqParse_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 0
	return a.Recorder
}

func (a *MoqParse_genType_anyParams) Text() *MoqParse_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 1
	return a.Recorder
}

func (a *MoqParse_genType_anyParams) LeftDelim() *MoqParse_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 2
	return a.Recorder
}

func (a *MoqParse_genType_anyParams) RightDelim() *MoqParse_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 3
	return a.Recorder
}

func (a *MoqParse_genType_anyParams) Funcs() *MoqParse_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 4
	return a.Recorder
}

func (r *MoqParse_genType_fnRecorder) Seq() *MoqParse_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqParse_genType_fnRecorder) NoSeq() *MoqParse_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqParse_genType_fnRecorder) ReturnResults(result1 map[string]*parse.Tree, result2 error) *MoqParse_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 map[string]*parse.Tree
			Result2 error
		}
		Sequence   uint32
		DoFn       MoqParse_genType_doFn
		DoReturnFn MoqParse_genType_doReturnFn
	}{
		Values: &struct {
			Result1 map[string]*parse.Tree
			Result2 error
		}{
			Result1: result1,
			Result2: result2,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqParse_genType_fnRecorder) AndDo(fn MoqParse_genType_doFn) *MoqParse_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqParse_genType_fnRecorder) DoReturnResults(fn MoqParse_genType_doReturnFn) *MoqParse_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 map[string]*parse.Tree
			Result2 error
		}
		Sequence   uint32
		DoFn       MoqParse_genType_doFn
		DoReturnFn MoqParse_genType_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqParse_genType_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqParse_genType_resultsByParams
	for n, res := range r.Moq.ResultsByParams {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqParse_genType_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqParse_genType_paramsKey]*MoqParse_genType_results{},
		}
		r.Moq.ResultsByParams = append(r.Moq.ResultsByParams, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams) {
			copy(r.Moq.ResultsByParams[insertAt+1:], r.Moq.ResultsByParams[insertAt:0])
			r.Moq.ResultsByParams[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqParse_genType_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqParse_genType_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqParse_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 map[string]*parse.Tree
					Result2 error
				}
				Sequence   uint32
				DoFn       MoqParse_genType_doFn
				DoReturnFn MoqParse_genType_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqParse_genType) PrettyParams(params MoqParse_genType_params) string {
	return fmt.Sprintf("Parse_genType(%#v, %#v, %#v, %#v, %#v)", params.Name, params.Text, params.LeftDelim, params.RightDelim, params.Funcs)
}

func (m *MoqParse_genType) ParamsKey(params MoqParse_genType_params, anyParams uint64) MoqParse_genType_paramsKey {
	m.Scene.T.Helper()
	var nameUsed string
	var nameUsedHash hash.Hash
	if anyParams&(1<<0) == 0 {
		if m.Runtime.ParameterIndexing.Name == moq.ParamIndexByValue {
			nameUsed = params.Name
		} else {
			nameUsedHash = hash.DeepHash(params.Name)
		}
	}
	var textUsed string
	var textUsedHash hash.Hash
	if anyParams&(1<<1) == 0 {
		if m.Runtime.ParameterIndexing.Text == moq.ParamIndexByValue {
			textUsed = params.Text
		} else {
			textUsedHash = hash.DeepHash(params.Text)
		}
	}
	var leftDelimUsed string
	var leftDelimUsedHash hash.Hash
	if anyParams&(1<<2) == 0 {
		if m.Runtime.ParameterIndexing.LeftDelim == moq.ParamIndexByValue {
			leftDelimUsed = params.LeftDelim
		} else {
			leftDelimUsedHash = hash.DeepHash(params.LeftDelim)
		}
	}
	var rightDelimUsed string
	var rightDelimUsedHash hash.Hash
	if anyParams&(1<<3) == 0 {
		if m.Runtime.ParameterIndexing.RightDelim == moq.ParamIndexByValue {
			rightDelimUsed = params.RightDelim
		} else {
			rightDelimUsedHash = hash.DeepHash(params.RightDelim)
		}
	}
	var funcsUsedHash hash.Hash
	if anyParams&(1<<4) == 0 {
		if m.Runtime.ParameterIndexing.Funcs == moq.ParamIndexByValue {
			m.Scene.T.Fatalf("The funcs parameter can't be indexed by value")
		}
		funcsUsedHash = hash.DeepHash(params.Funcs)
	}
	return MoqParse_genType_paramsKey{
		Params: struct{ Name, Text, LeftDelim, RightDelim string }{
			Name:       nameUsed,
			Text:       textUsed,
			LeftDelim:  leftDelimUsed,
			RightDelim: rightDelimUsed,
		},
		Hashes: struct {
			Name, Text, LeftDelim, RightDelim hash.Hash
			Funcs                             hash.Hash
		}{
			Name:       nameUsedHash,
			Text:       textUsedHash,
			LeftDelim:  leftDelimUsedHash,
			RightDelim: rightDelimUsedHash,
			Funcs:      funcsUsedHash,
		},
	}
}

// Reset resets the state of the moq
func (m *MoqParse_genType) Reset() { m.ResultsByParams = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqParse_genType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams(results.Params))
			}
		}
	}
}
