// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package strconv

import (
	"fmt"
	"math/bits"
	"sync/atomic"

	"moqueries.org/runtime/hash"
	"moqueries.org/runtime/moq"
)

// AppendFloat_genType is the fabricated implementation type of this mock
// (emitted when mocking functions directly and not from a function type)
type AppendFloat_genType func(dst []byte, f float64, fmt byte, prec, bitSize int) []byte

// MoqAppendFloat_genType holds the state of a moq of the AppendFloat_genType
// type
type MoqAppendFloat_genType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqAppendFloat_genType_mock

	ResultsByParams []MoqAppendFloat_genType_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			Dst     moq.ParamIndexing
			F       moq.ParamIndexing
			Fmt     moq.ParamIndexing
			Prec    moq.ParamIndexing
			BitSize moq.ParamIndexing
		}
	}
}

// MoqAppendFloat_genType_mock isolates the mock interface of the
// AppendFloat_genType type
type MoqAppendFloat_genType_mock struct {
	Moq *MoqAppendFloat_genType
}

// MoqAppendFloat_genType_params holds the params of the AppendFloat_genType
// type
type MoqAppendFloat_genType_params struct {
	Dst           []byte
	F             float64
	Fmt           byte
	Prec, BitSize int
}

// MoqAppendFloat_genType_paramsKey holds the map key params of the
// AppendFloat_genType type
type MoqAppendFloat_genType_paramsKey struct {
	Params struct {
		F             float64
		Fmt           byte
		Prec, BitSize int
	}
	Hashes struct {
		Dst           hash.Hash
		F             hash.Hash
		Fmt           hash.Hash
		Prec, BitSize hash.Hash
	}
}

// MoqAppendFloat_genType_resultsByParams contains the results for a given set
// of parameters for the AppendFloat_genType type
type MoqAppendFloat_genType_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqAppendFloat_genType_paramsKey]*MoqAppendFloat_genType_results
}

// MoqAppendFloat_genType_doFn defines the type of function needed when calling
// AndDo for the AppendFloat_genType type
type MoqAppendFloat_genType_doFn func(dst []byte, f float64, fmt byte, prec, bitSize int)

// MoqAppendFloat_genType_doReturnFn defines the type of function needed when
// calling DoReturnResults for the AppendFloat_genType type
type MoqAppendFloat_genType_doReturnFn func(dst []byte, f float64, fmt byte, prec, bitSize int) []byte

// MoqAppendFloat_genType_results holds the results of the AppendFloat_genType
// type
type MoqAppendFloat_genType_results struct {
	Params  MoqAppendFloat_genType_params
	Results []struct {
		Values *struct {
			Result1 []byte
		}
		Sequence   uint32
		DoFn       MoqAppendFloat_genType_doFn
		DoReturnFn MoqAppendFloat_genType_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqAppendFloat_genType_fnRecorder routes recorded function calls to the
// MoqAppendFloat_genType moq
type MoqAppendFloat_genType_fnRecorder struct {
	Params    MoqAppendFloat_genType_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqAppendFloat_genType_results
	Moq       *MoqAppendFloat_genType
}

// MoqAppendFloat_genType_anyParams isolates the any params functions of the
// AppendFloat_genType type
type MoqAppendFloat_genType_anyParams struct {
	Recorder *MoqAppendFloat_genType_fnRecorder
}

// NewMoqAppendFloat_genType creates a new moq of the AppendFloat_genType type
func NewMoqAppendFloat_genType(scene *moq.Scene, config *moq.Config) *MoqAppendFloat_genType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqAppendFloat_genType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqAppendFloat_genType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				Dst     moq.ParamIndexing
				F       moq.ParamIndexing
				Fmt     moq.ParamIndexing
				Prec    moq.ParamIndexing
				BitSize moq.ParamIndexing
			}
		}{ParameterIndexing: struct {
			Dst     moq.ParamIndexing
			F       moq.ParamIndexing
			Fmt     moq.ParamIndexing
			Prec    moq.ParamIndexing
			BitSize moq.ParamIndexing
		}{
			Dst:     moq.ParamIndexByHash,
			F:       moq.ParamIndexByValue,
			Fmt:     moq.ParamIndexByValue,
			Prec:    moq.ParamIndexByValue,
			BitSize: moq.ParamIndexByValue,
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the moq implementation of the AppendFloat_genType type
func (m *MoqAppendFloat_genType) Mock() AppendFloat_genType {
	return func(dst []byte, f float64, fmt byte, prec, bitSize int) []byte {
		m.Scene.T.Helper()
		moq := &MoqAppendFloat_genType_mock{Moq: m}
		return moq.Fn(dst, f, fmt, prec, bitSize)
	}
}

func (m *MoqAppendFloat_genType_mock) Fn(dst []byte, f float64, fmt byte, prec, bitSize int) (result1 []byte) {
	m.Moq.Scene.T.Helper()
	params := MoqAppendFloat_genType_params{
		Dst:     dst,
		F:       f,
		Fmt:     fmt,
		Prec:    prec,
		BitSize: bitSize,
	}
	var results *MoqAppendFloat_genType_results
	for _, resultsByParams := range m.Moq.ResultsByParams {
		paramsKey := m.Moq.ParamsKey(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn(dst, f, fmt, prec, bitSize)
	}

	if result.Values != nil {
		result1 = result.Values.Result1
	}
	if result.DoReturnFn != nil {
		result1 = result.DoReturnFn(dst, f, fmt, prec, bitSize)
	}
	return
}

func (m *MoqAppendFloat_genType) OnCall(dst []byte, f float64, fmt byte, prec, bitSize int) *MoqAppendFloat_genType_fnRecorder {
	return &MoqAppendFloat_genType_fnRecorder{
		Params: MoqAppendFloat_genType_params{
			Dst:     dst,
			F:       f,
			Fmt:     fmt,
			Prec:    prec,
			BitSize: bitSize,
		},
		Sequence: m.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m,
	}
}

func (r *MoqAppendFloat_genType_fnRecorder) Any() *MoqAppendFloat_genType_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	return &MoqAppendFloat_genType_anyParams{Recorder: r}
}

func (a *MoqAppendFloat_genType_anyParams) Dst() *MoqAppendFloat_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 0
	return a.Recorder
}

func (a *MoqAppendFloat_genType_anyParams) F() *MoqAppendFloat_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 1
	return a.Recorder
}

func (a *MoqAppendFloat_genType_anyParams) Fmt() *MoqAppendFloat_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 2
	return a.Recorder
}

func (a *MoqAppendFloat_genType_anyParams) Prec() *MoqAppendFloat_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 3
	return a.Recorder
}

func (a *MoqAppendFloat_genType_anyParams) BitSize() *MoqAppendFloat_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 4
	return a.Recorder
}

func (r *MoqAppendFloat_genType_fnRecorder) Seq() *MoqAppendFloat_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqAppendFloat_genType_fnRecorder) NoSeq() *MoqAppendFloat_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqAppendFloat_genType_fnRecorder) ReturnResults(result1 []byte) *MoqAppendFloat_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 []byte
		}
		Sequence   uint32
		DoFn       MoqAppendFloat_genType_doFn
		DoReturnFn MoqAppendFloat_genType_doReturnFn
	}{
		Values: &struct {
			Result1 []byte
		}{
			Result1: result1,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqAppendFloat_genType_fnRecorder) AndDo(fn MoqAppendFloat_genType_doFn) *MoqAppendFloat_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqAppendFloat_genType_fnRecorder) DoReturnResults(fn MoqAppendFloat_genType_doReturnFn) *MoqAppendFloat_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 []byte
		}
		Sequence   uint32
		DoFn       MoqAppendFloat_genType_doFn
		DoReturnFn MoqAppendFloat_genType_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqAppendFloat_genType_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqAppendFloat_genType_resultsByParams
	for n, res := range r.Moq.ResultsByParams {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqAppendFloat_genType_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqAppendFloat_genType_paramsKey]*MoqAppendFloat_genType_results{},
		}
		r.Moq.ResultsByParams = append(r.Moq.ResultsByParams, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams) {
			copy(r.Moq.ResultsByParams[insertAt+1:], r.Moq.ResultsByParams[insertAt:0])
			r.Moq.ResultsByParams[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqAppendFloat_genType_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqAppendFloat_genType_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqAppendFloat_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 []byte
				}
				Sequence   uint32
				DoFn       MoqAppendFloat_genType_doFn
				DoReturnFn MoqAppendFloat_genType_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqAppendFloat_genType) PrettyParams(params MoqAppendFloat_genType_params) string {
	return fmt.Sprintf("AppendFloat_genType(%#v, %#v, %#v, %#v, %#v)", params.Dst, params.F, params.Fmt, params.Prec, params.BitSize)
}

func (m *MoqAppendFloat_genType) ParamsKey(params MoqAppendFloat_genType_params, anyParams uint64) MoqAppendFloat_genType_paramsKey {
	m.Scene.T.Helper()
	var dstUsedHash hash.Hash
	if anyParams&(1<<0) == 0 {
		if m.Runtime.ParameterIndexing.Dst == moq.ParamIndexByValue {
			m.Scene.T.Fatalf("The dst parameter can't be indexed by value")
		}
		dstUsedHash = hash.DeepHash(params.Dst)
	}
	var fUsed float64
	var fUsedHash hash.Hash
	if anyParams&(1<<1) == 0 {
		if m.Runtime.ParameterIndexing.F == moq.ParamIndexByValue {
			fUsed = params.F
		} else {
			fUsedHash = hash.DeepHash(params.F)
		}
	}
	var fmtUsed byte
	var fmtUsedHash hash.Hash
	if anyParams&(1<<2) == 0 {
		if m.Runtime.ParameterIndexing.Fmt == moq.ParamIndexByValue {
			fmtUsed = params.Fmt
		} else {
			fmtUsedHash = hash.DeepHash(params.Fmt)
		}
	}
	var precUsed int
	var precUsedHash hash.Hash
	if anyParams&(1<<3) == 0 {
		if m.Runtime.ParameterIndexing.Prec == moq.ParamIndexByValue {
			precUsed = params.Prec
		} else {
			precUsedHash = hash.DeepHash(params.Prec)
		}
	}
	var bitSizeUsed int
	var bitSizeUsedHash hash.Hash
	if anyParams&(1<<4) == 0 {
		if m.Runtime.ParameterIndexing.BitSize == moq.ParamIndexByValue {
			bitSizeUsed = params.BitSize
		} else {
			bitSizeUsedHash = hash.DeepHash(params.BitSize)
		}
	}
	return MoqAppendFloat_genType_paramsKey{
		Params: struct {
			F             float64
			Fmt           byte
			Prec, BitSize int
		}{
			F:       fUsed,
			Fmt:     fmtUsed,
			Prec:    precUsed,
			BitSize: bitSizeUsed,
		},
		Hashes: struct {
			Dst           hash.Hash
			F             hash.Hash
			Fmt           hash.Hash
			Prec, BitSize hash.Hash
		}{
			Dst:     dstUsedHash,
			F:       fUsedHash,
			Fmt:     fmtUsedHash,
			Prec:    precUsedHash,
			BitSize: bitSizeUsedHash,
		},
	}
}

// Reset resets the state of the moq
func (m *MoqAppendFloat_genType) Reset() { m.ResultsByParams = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqAppendFloat_genType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams(results.Params))
			}
		}
	}
}
