// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package pkix

import (
	"crypto/x509/pkix"
	"fmt"
	"math/bits"
	"sync/atomic"

	"moqueries.org/runtime/moq"
)

// The following type assertion assures that pkix.Name_genType is mocked
// completely
var _ Name_genType = (*MoqName_genType_mock)(nil)

// Name_genType is the fabricated implementation type of this mock (emitted
// when mocking a collections of methods directly and not from an interface
// type)
type Name_genType interface {
	ToRDNSequence() (ret pkix.RDNSequence)
	String() string
}

// MoqName_genType holds the state of a moq of the Name_genType type
type MoqName_genType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqName_genType_mock

	ResultsByParams_ToRDNSequence []MoqName_genType_ToRDNSequence_resultsByParams
	ResultsByParams_String        []MoqName_genType_String_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			ToRDNSequence struct{}
			String        struct{}
		}
	}
}

// MoqName_genType_mock isolates the mock interface of the Name_genType type
type MoqName_genType_mock struct {
	Moq *MoqName_genType
}

// MoqName_genType_recorder isolates the recorder interface of the Name_genType
// type
type MoqName_genType_recorder struct {
	Moq *MoqName_genType
}

// MoqName_genType_ToRDNSequence_params holds the params of the Name_genType
// type
type MoqName_genType_ToRDNSequence_params struct{}

// MoqName_genType_ToRDNSequence_paramsKey holds the map key params of the
// Name_genType type
type MoqName_genType_ToRDNSequence_paramsKey struct {
	Params struct{}
	Hashes struct{}
}

// MoqName_genType_ToRDNSequence_resultsByParams contains the results for a
// given set of parameters for the Name_genType type
type MoqName_genType_ToRDNSequence_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqName_genType_ToRDNSequence_paramsKey]*MoqName_genType_ToRDNSequence_results
}

// MoqName_genType_ToRDNSequence_doFn defines the type of function needed when
// calling AndDo for the Name_genType type
type MoqName_genType_ToRDNSequence_doFn func()

// MoqName_genType_ToRDNSequence_doReturnFn defines the type of function needed
// when calling DoReturnResults for the Name_genType type
type MoqName_genType_ToRDNSequence_doReturnFn func() (ret pkix.RDNSequence)

// MoqName_genType_ToRDNSequence_results holds the results of the Name_genType
// type
type MoqName_genType_ToRDNSequence_results struct {
	Params  MoqName_genType_ToRDNSequence_params
	Results []struct {
		Values     *struct{ Ret pkix.RDNSequence }
		Sequence   uint32
		DoFn       MoqName_genType_ToRDNSequence_doFn
		DoReturnFn MoqName_genType_ToRDNSequence_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqName_genType_ToRDNSequence_fnRecorder routes recorded function calls to
// the MoqName_genType moq
type MoqName_genType_ToRDNSequence_fnRecorder struct {
	Params    MoqName_genType_ToRDNSequence_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqName_genType_ToRDNSequence_results
	Moq       *MoqName_genType
}

// MoqName_genType_ToRDNSequence_anyParams isolates the any params functions of
// the Name_genType type
type MoqName_genType_ToRDNSequence_anyParams struct {
	Recorder *MoqName_genType_ToRDNSequence_fnRecorder
}

// MoqName_genType_String_params holds the params of the Name_genType type
type MoqName_genType_String_params struct{}

// MoqName_genType_String_paramsKey holds the map key params of the
// Name_genType type
type MoqName_genType_String_paramsKey struct {
	Params struct{}
	Hashes struct{}
}

// MoqName_genType_String_resultsByParams contains the results for a given set
// of parameters for the Name_genType type
type MoqName_genType_String_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqName_genType_String_paramsKey]*MoqName_genType_String_results
}

// MoqName_genType_String_doFn defines the type of function needed when calling
// AndDo for the Name_genType type
type MoqName_genType_String_doFn func()

// MoqName_genType_String_doReturnFn defines the type of function needed when
// calling DoReturnResults for the Name_genType type
type MoqName_genType_String_doReturnFn func() string

// MoqName_genType_String_results holds the results of the Name_genType type
type MoqName_genType_String_results struct {
	Params  MoqName_genType_String_params
	Results []struct {
		Values *struct {
			Result1 string
		}
		Sequence   uint32
		DoFn       MoqName_genType_String_doFn
		DoReturnFn MoqName_genType_String_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqName_genType_String_fnRecorder routes recorded function calls to the
// MoqName_genType moq
type MoqName_genType_String_fnRecorder struct {
	Params    MoqName_genType_String_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqName_genType_String_results
	Moq       *MoqName_genType
}

// MoqName_genType_String_anyParams isolates the any params functions of the
// Name_genType type
type MoqName_genType_String_anyParams struct {
	Recorder *MoqName_genType_String_fnRecorder
}

// NewMoqName_genType creates a new moq of the Name_genType type
func NewMoqName_genType(scene *moq.Scene, config *moq.Config) *MoqName_genType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqName_genType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqName_genType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				ToRDNSequence struct{}
				String        struct{}
			}
		}{ParameterIndexing: struct {
			ToRDNSequence struct{}
			String        struct{}
		}{
			ToRDNSequence: struct{}{},
			String:        struct{}{},
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the mock implementation of the Name_genType type
func (m *MoqName_genType) Mock() *MoqName_genType_mock { return m.Moq }

func (m *MoqName_genType_mock) ToRDNSequence() (ret pkix.RDNSequence) {
	m.Moq.Scene.T.Helper()
	params := MoqName_genType_ToRDNSequence_params{}
	var results *MoqName_genType_ToRDNSequence_results
	for _, resultsByParams := range m.Moq.ResultsByParams_ToRDNSequence {
		paramsKey := m.Moq.ParamsKey_ToRDNSequence(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams_ToRDNSequence(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams_ToRDNSequence(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams_ToRDNSequence(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn()
	}

	if result.Values != nil {
		ret = result.Values.Ret
	}
	if result.DoReturnFn != nil {
		ret = result.DoReturnFn()
	}
	return
}

func (m *MoqName_genType_mock) String() (result1 string) {
	m.Moq.Scene.T.Helper()
	params := MoqName_genType_String_params{}
	var results *MoqName_genType_String_results
	for _, resultsByParams := range m.Moq.ResultsByParams_String {
		paramsKey := m.Moq.ParamsKey_String(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams_String(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams_String(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams_String(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn()
	}

	if result.Values != nil {
		result1 = result.Values.Result1
	}
	if result.DoReturnFn != nil {
		result1 = result.DoReturnFn()
	}
	return
}

// OnCall returns the recorder implementation of the Name_genType type
func (m *MoqName_genType) OnCall() *MoqName_genType_recorder {
	return &MoqName_genType_recorder{
		Moq: m,
	}
}

func (m *MoqName_genType_recorder) ToRDNSequence() *MoqName_genType_ToRDNSequence_fnRecorder {
	return &MoqName_genType_ToRDNSequence_fnRecorder{
		Params:   MoqName_genType_ToRDNSequence_params{},
		Sequence: m.Moq.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m.Moq,
	}
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) Any() *MoqName_genType_ToRDNSequence_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_ToRDNSequence(r.Params))
		return nil
	}
	return &MoqName_genType_ToRDNSequence_anyParams{Recorder: r}
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) Seq() *MoqName_genType_ToRDNSequence_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_ToRDNSequence(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) NoSeq() *MoqName_genType_ToRDNSequence_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_ToRDNSequence(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) ReturnResults(ret pkix.RDNSequence) *MoqName_genType_ToRDNSequence_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values     *struct{ Ret pkix.RDNSequence }
		Sequence   uint32
		DoFn       MoqName_genType_ToRDNSequence_doFn
		DoReturnFn MoqName_genType_ToRDNSequence_doReturnFn
	}{
		Values: &struct{ Ret pkix.RDNSequence }{
			Ret: ret,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) AndDo(fn MoqName_genType_ToRDNSequence_doFn) *MoqName_genType_ToRDNSequence_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) DoReturnResults(fn MoqName_genType_ToRDNSequence_doReturnFn) *MoqName_genType_ToRDNSequence_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values     *struct{ Ret pkix.RDNSequence }
		Sequence   uint32
		DoFn       MoqName_genType_ToRDNSequence_doFn
		DoReturnFn MoqName_genType_ToRDNSequence_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqName_genType_ToRDNSequence_resultsByParams
	for n, res := range r.Moq.ResultsByParams_ToRDNSequence {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqName_genType_ToRDNSequence_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqName_genType_ToRDNSequence_paramsKey]*MoqName_genType_ToRDNSequence_results{},
		}
		r.Moq.ResultsByParams_ToRDNSequence = append(r.Moq.ResultsByParams_ToRDNSequence, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams_ToRDNSequence) {
			copy(r.Moq.ResultsByParams_ToRDNSequence[insertAt+1:], r.Moq.ResultsByParams_ToRDNSequence[insertAt:0])
			r.Moq.ResultsByParams_ToRDNSequence[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey_ToRDNSequence(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqName_genType_ToRDNSequence_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqName_genType_ToRDNSequence_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqName_genType_ToRDNSequence_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values     *struct{ Ret pkix.RDNSequence }
				Sequence   uint32
				DoFn       MoqName_genType_ToRDNSequence_doFn
				DoReturnFn MoqName_genType_ToRDNSequence_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqName_genType) PrettyParams_ToRDNSequence(params MoqName_genType_ToRDNSequence_params) string {
	return fmt.Sprintf("ToRDNSequence()")
}

func (m *MoqName_genType) ParamsKey_ToRDNSequence(params MoqName_genType_ToRDNSequence_params, anyParams uint64) MoqName_genType_ToRDNSequence_paramsKey {
	m.Scene.T.Helper()
	return MoqName_genType_ToRDNSequence_paramsKey{
		Params: struct{}{},
		Hashes: struct{}{},
	}
}

func (m *MoqName_genType_recorder) String() *MoqName_genType_String_fnRecorder {
	return &MoqName_genType_String_fnRecorder{
		Params:   MoqName_genType_String_params{},
		Sequence: m.Moq.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m.Moq,
	}
}

func (r *MoqName_genType_String_fnRecorder) Any() *MoqName_genType_String_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_String(r.Params))
		return nil
	}
	return &MoqName_genType_String_anyParams{Recorder: r}
}

func (r *MoqName_genType_String_fnRecorder) Seq() *MoqName_genType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_String(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqName_genType_String_fnRecorder) NoSeq() *MoqName_genType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_String(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqName_genType_String_fnRecorder) ReturnResults(result1 string) *MoqName_genType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 string
		}
		Sequence   uint32
		DoFn       MoqName_genType_String_doFn
		DoReturnFn MoqName_genType_String_doReturnFn
	}{
		Values: &struct {
			Result1 string
		}{
			Result1: result1,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqName_genType_String_fnRecorder) AndDo(fn MoqName_genType_String_doFn) *MoqName_genType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqName_genType_String_fnRecorder) DoReturnResults(fn MoqName_genType_String_doReturnFn) *MoqName_genType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 string
		}
		Sequence   uint32
		DoFn       MoqName_genType_String_doFn
		DoReturnFn MoqName_genType_String_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqName_genType_String_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqName_genType_String_resultsByParams
	for n, res := range r.Moq.ResultsByParams_String {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqName_genType_String_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqName_genType_String_paramsKey]*MoqName_genType_String_results{},
		}
		r.Moq.ResultsByParams_String = append(r.Moq.ResultsByParams_String, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams_String) {
			copy(r.Moq.ResultsByParams_String[insertAt+1:], r.Moq.ResultsByParams_String[insertAt:0])
			r.Moq.ResultsByParams_String[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey_String(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqName_genType_String_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqName_genType_String_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqName_genType_String_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 string
				}
				Sequence   uint32
				DoFn       MoqName_genType_String_doFn
				DoReturnFn MoqName_genType_String_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqName_genType) PrettyParams_String(params MoqName_genType_String_params) string {
	return fmt.Sprintf("String()")
}

func (m *MoqName_genType) ParamsKey_String(params MoqName_genType_String_params, anyParams uint64) MoqName_genType_String_paramsKey {
	m.Scene.T.Helper()
	return MoqName_genType_String_paramsKey{
		Params: struct{}{},
		Hashes: struct{}{},
	}
}

// Reset resets the state of the moq
func (m *MoqName_genType) Reset() {
	m.ResultsByParams_ToRDNSequence = nil
	m.ResultsByParams_String = nil
}

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqName_genType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams_ToRDNSequence {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams_ToRDNSequence(results.Params))
			}
		}
	}
	for _, res := range m.ResultsByParams_String {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams_String(results.Params))
			}
		}
	}
}
