// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package syscall

import (
	"fmt"
	"math/bits"
	"sync/atomic"
	"syscall"

	"moqueries.org/runtime/hash"
	"moqueries.org/runtime/moq"
)

// Wait4_genType is the fabricated implementation type of this mock (emitted
// when mocking functions directly and not from a function type)
type Wait4_genType func(pid int, wstatus *syscall.WaitStatus, options int, rusage *syscall.Rusage) (wpid int, err error)

// MoqWait4_genType holds the state of a moq of the Wait4_genType type
type MoqWait4_genType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqWait4_genType_mock

	ResultsByParams []MoqWait4_genType_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			Pid     moq.ParamIndexing
			Wstatus moq.ParamIndexing
			Options moq.ParamIndexing
			Rusage  moq.ParamIndexing
		}
	}
}

// MoqWait4_genType_mock isolates the mock interface of the Wait4_genType type
type MoqWait4_genType_mock struct {
	Moq *MoqWait4_genType
}

// MoqWait4_genType_params holds the params of the Wait4_genType type
type MoqWait4_genType_params struct {
	Pid     int
	Wstatus *syscall.WaitStatus
	Options int
	Rusage  *syscall.Rusage
}

// MoqWait4_genType_paramsKey holds the map key params of the Wait4_genType
// type
type MoqWait4_genType_paramsKey struct {
	Params struct {
		Pid     int
		Wstatus *syscall.WaitStatus
		Options int
		Rusage  *syscall.Rusage
	}
	Hashes struct {
		Pid     hash.Hash
		Wstatus hash.Hash
		Options hash.Hash
		Rusage  hash.Hash
	}
}

// MoqWait4_genType_resultsByParams contains the results for a given set of
// parameters for the Wait4_genType type
type MoqWait4_genType_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqWait4_genType_paramsKey]*MoqWait4_genType_results
}

// MoqWait4_genType_doFn defines the type of function needed when calling AndDo
// for the Wait4_genType type
type MoqWait4_genType_doFn func(pid int, wstatus *syscall.WaitStatus, options int, rusage *syscall.Rusage)

// MoqWait4_genType_doReturnFn defines the type of function needed when calling
// DoReturnResults for the Wait4_genType type
type MoqWait4_genType_doReturnFn func(pid int, wstatus *syscall.WaitStatus, options int, rusage *syscall.Rusage) (wpid int, err error)

// MoqWait4_genType_results holds the results of the Wait4_genType type
type MoqWait4_genType_results struct {
	Params  MoqWait4_genType_params
	Results []struct {
		Values *struct {
			Wpid int
			Err  error
		}
		Sequence   uint32
		DoFn       MoqWait4_genType_doFn
		DoReturnFn MoqWait4_genType_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqWait4_genType_fnRecorder routes recorded function calls to the
// MoqWait4_genType moq
type MoqWait4_genType_fnRecorder struct {
	Params    MoqWait4_genType_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqWait4_genType_results
	Moq       *MoqWait4_genType
}

// MoqWait4_genType_anyParams isolates the any params functions of the
// Wait4_genType type
type MoqWait4_genType_anyParams struct {
	Recorder *MoqWait4_genType_fnRecorder
}

// NewMoqWait4_genType creates a new moq of the Wait4_genType type
func NewMoqWait4_genType(scene *moq.Scene, config *moq.Config) *MoqWait4_genType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqWait4_genType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqWait4_genType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				Pid     moq.ParamIndexing
				Wstatus moq.ParamIndexing
				Options moq.ParamIndexing
				Rusage  moq.ParamIndexing
			}
		}{ParameterIndexing: struct {
			Pid     moq.ParamIndexing
			Wstatus moq.ParamIndexing
			Options moq.ParamIndexing
			Rusage  moq.ParamIndexing
		}{
			Pid:     moq.ParamIndexByValue,
			Wstatus: moq.ParamIndexByHash,
			Options: moq.ParamIndexByValue,
			Rusage:  moq.ParamIndexByHash,
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the moq implementation of the Wait4_genType type
func (m *MoqWait4_genType) Mock() Wait4_genType {
	return func(pid int, wstatus *syscall.WaitStatus, options int, rusage *syscall.Rusage) (_ int, _ error) {
		m.Scene.T.Helper()
		moq := &MoqWait4_genType_mock{Moq: m}
		return moq.Fn(pid, wstatus, options, rusage)
	}
}

func (m *MoqWait4_genType_mock) Fn(pid int, wstatus *syscall.WaitStatus, options int, rusage *syscall.Rusage) (wpid int, err error) {
	m.Moq.Scene.T.Helper()
	params := MoqWait4_genType_params{
		Pid:     pid,
		Wstatus: wstatus,
		Options: options,
		Rusage:  rusage,
	}
	var results *MoqWait4_genType_results
	for _, resultsByParams := range m.Moq.ResultsByParams {
		paramsKey := m.Moq.ParamsKey(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn(pid, wstatus, options, rusage)
	}

	if result.Values != nil {
		wpid = result.Values.Wpid
		err = result.Values.Err
	}
	if result.DoReturnFn != nil {
		wpid, err = result.DoReturnFn(pid, wstatus, options, rusage)
	}
	return
}

func (m *MoqWait4_genType) OnCall(pid int, wstatus *syscall.WaitStatus, options int, rusage *syscall.Rusage) *MoqWait4_genType_fnRecorder {
	return &MoqWait4_genType_fnRecorder{
		Params: MoqWait4_genType_params{
			Pid:     pid,
			Wstatus: wstatus,
			Options: options,
			Rusage:  rusage,
		},
		Sequence: m.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m,
	}
}

func (r *MoqWait4_genType_fnRecorder) Any() *MoqWait4_genType_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	return &MoqWait4_genType_anyParams{Recorder: r}
}

func (a *MoqWait4_genType_anyParams) Pid() *MoqWait4_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 0
	return a.Recorder
}

func (a *MoqWait4_genType_anyParams) Wstatus() *MoqWait4_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 1
	return a.Recorder
}

func (a *MoqWait4_genType_anyParams) Options() *MoqWait4_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 2
	return a.Recorder
}

func (a *MoqWait4_genType_anyParams) Rusage() *MoqWait4_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 3
	return a.Recorder
}

func (r *MoqWait4_genType_fnRecorder) Seq() *MoqWait4_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqWait4_genType_fnRecorder) NoSeq() *MoqWait4_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqWait4_genType_fnRecorder) ReturnResults(wpid int, err error) *MoqWait4_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Wpid int
			Err  error
		}
		Sequence   uint32
		DoFn       MoqWait4_genType_doFn
		DoReturnFn MoqWait4_genType_doReturnFn
	}{
		Values: &struct {
			Wpid int
			Err  error
		}{
			Wpid: wpid,
			Err:  err,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqWait4_genType_fnRecorder) AndDo(fn MoqWait4_genType_doFn) *MoqWait4_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqWait4_genType_fnRecorder) DoReturnResults(fn MoqWait4_genType_doReturnFn) *MoqWait4_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Wpid int
			Err  error
		}
		Sequence   uint32
		DoFn       MoqWait4_genType_doFn
		DoReturnFn MoqWait4_genType_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqWait4_genType_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqWait4_genType_resultsByParams
	for n, res := range r.Moq.ResultsByParams {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqWait4_genType_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqWait4_genType_paramsKey]*MoqWait4_genType_results{},
		}
		r.Moq.ResultsByParams = append(r.Moq.ResultsByParams, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams) {
			copy(r.Moq.ResultsByParams[insertAt+1:], r.Moq.ResultsByParams[insertAt:0])
			r.Moq.ResultsByParams[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqWait4_genType_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqWait4_genType_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqWait4_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Wpid int
					Err  error
				}
				Sequence   uint32
				DoFn       MoqWait4_genType_doFn
				DoReturnFn MoqWait4_genType_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqWait4_genType) PrettyParams(params MoqWait4_genType_params) string {
	return fmt.Sprintf("Wait4_genType(%#v, %#v, %#v, %#v)", params.Pid, params.Wstatus, params.Options, params.Rusage)
}

func (m *MoqWait4_genType) ParamsKey(params MoqWait4_genType_params, anyParams uint64) MoqWait4_genType_paramsKey {
	m.Scene.T.Helper()
	var pidUsed int
	var pidUsedHash hash.Hash
	if anyParams&(1<<0) == 0 {
		if m.Runtime.ParameterIndexing.Pid == moq.ParamIndexByValue {
			pidUsed = params.Pid
		} else {
			pidUsedHash = hash.DeepHash(params.Pid)
		}
	}
	var wstatusUsed *syscall.WaitStatus
	var wstatusUsedHash hash.Hash
	if anyParams&(1<<1) == 0 {
		if m.Runtime.ParameterIndexing.Wstatus == moq.ParamIndexByValue {
			wstatusUsed = params.Wstatus
		} else {
			wstatusUsedHash = hash.DeepHash(params.Wstatus)
		}
	}
	var optionsUsed int
	var optionsUsedHash hash.Hash
	if anyParams&(1<<2) == 0 {
		if m.Runtime.ParameterIndexing.Options == moq.ParamIndexByValue {
			optionsUsed = params.Options
		} else {
			optionsUsedHash = hash.DeepHash(params.Options)
		}
	}
	var rusageUsed *syscall.Rusage
	var rusageUsedHash hash.Hash
	if anyParams&(1<<3) == 0 {
		if m.Runtime.ParameterIndexing.Rusage == moq.ParamIndexByValue {
			rusageUsed = params.Rusage
		} else {
			rusageUsedHash = hash.DeepHash(params.Rusage)
		}
	}
	return MoqWait4_genType_paramsKey{
		Params: struct {
			Pid     int
			Wstatus *syscall.WaitStatus
			Options int
			Rusage  *syscall.Rusage
		}{
			Pid:     pidUsed,
			Wstatus: wstatusUsed,
			Options: optionsUsed,
			Rusage:  rusageUsed,
		},
		Hashes: struct {
			Pid     hash.Hash
			Wstatus hash.Hash
			Options hash.Hash
			Rusage  hash.Hash
		}{
			Pid:     pidUsedHash,
			Wstatus: wstatusUsedHash,
			Options: optionsUsedHash,
			Rusage:  rusageUsedHash,
		},
	}
}

// Reset resets the state of the moq
func (m *MoqWait4_genType) Reset() { m.ResultsByParams = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqWait4_genType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams(results.Params))
			}
		}
	}
}
