// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package syscall

import (
	"fmt"
	"math/bits"
	"sync/atomic"

	"moqueries.org/runtime/hash"
	"moqueries.org/runtime/moq"
)

// Socket_genType is the fabricated implementation type of this mock (emitted
// when mocking functions directly and not from a function type)
type Socket_genType func(domain, typ, proto int) (fd int, err error)

// MoqSocket_genType holds the state of a moq of the Socket_genType type
type MoqSocket_genType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqSocket_genType_mock

	ResultsByParams []MoqSocket_genType_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			Domain moq.ParamIndexing
			Typ    moq.ParamIndexing
			Proto  moq.ParamIndexing
		}
	}
}

// MoqSocket_genType_mock isolates the mock interface of the Socket_genType
// type
type MoqSocket_genType_mock struct {
	Moq *MoqSocket_genType
}

// MoqSocket_genType_params holds the params of the Socket_genType type
type MoqSocket_genType_params struct{ Domain, Typ, Proto int }

// MoqSocket_genType_paramsKey holds the map key params of the Socket_genType
// type
type MoqSocket_genType_paramsKey struct {
	Params struct{ Domain, Typ, Proto int }
	Hashes struct{ Domain, Typ, Proto hash.Hash }
}

// MoqSocket_genType_resultsByParams contains the results for a given set of
// parameters for the Socket_genType type
type MoqSocket_genType_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqSocket_genType_paramsKey]*MoqSocket_genType_results
}

// MoqSocket_genType_doFn defines the type of function needed when calling
// AndDo for the Socket_genType type
type MoqSocket_genType_doFn func(domain, typ, proto int)

// MoqSocket_genType_doReturnFn defines the type of function needed when
// calling DoReturnResults for the Socket_genType type
type MoqSocket_genType_doReturnFn func(domain, typ, proto int) (fd int, err error)

// MoqSocket_genType_results holds the results of the Socket_genType type
type MoqSocket_genType_results struct {
	Params  MoqSocket_genType_params
	Results []struct {
		Values *struct {
			Fd  int
			Err error
		}
		Sequence   uint32
		DoFn       MoqSocket_genType_doFn
		DoReturnFn MoqSocket_genType_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqSocket_genType_fnRecorder routes recorded function calls to the
// MoqSocket_genType moq
type MoqSocket_genType_fnRecorder struct {
	Params    MoqSocket_genType_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqSocket_genType_results
	Moq       *MoqSocket_genType
}

// MoqSocket_genType_anyParams isolates the any params functions of the
// Socket_genType type
type MoqSocket_genType_anyParams struct {
	Recorder *MoqSocket_genType_fnRecorder
}

// NewMoqSocket_genType creates a new moq of the Socket_genType type
func NewMoqSocket_genType(scene *moq.Scene, config *moq.Config) *MoqSocket_genType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqSocket_genType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqSocket_genType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				Domain moq.ParamIndexing
				Typ    moq.ParamIndexing
				Proto  moq.ParamIndexing
			}
		}{ParameterIndexing: struct {
			Domain moq.ParamIndexing
			Typ    moq.ParamIndexing
			Proto  moq.ParamIndexing
		}{
			Domain: moq.ParamIndexByValue,
			Typ:    moq.ParamIndexByValue,
			Proto:  moq.ParamIndexByValue,
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the moq implementation of the Socket_genType type
func (m *MoqSocket_genType) Mock() Socket_genType {
	return func(domain, typ, proto int) (_ int, _ error) {
		m.Scene.T.Helper()
		moq := &MoqSocket_genType_mock{Moq: m}
		return moq.Fn(domain, typ, proto)
	}
}

func (m *MoqSocket_genType_mock) Fn(domain, typ, proto int) (fd int, err error) {
	m.Moq.Scene.T.Helper()
	params := MoqSocket_genType_params{
		Domain: domain,
		Typ:    typ,
		Proto:  proto,
	}
	var results *MoqSocket_genType_results
	for _, resultsByParams := range m.Moq.ResultsByParams {
		paramsKey := m.Moq.ParamsKey(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn(domain, typ, proto)
	}

	if result.Values != nil {
		fd = result.Values.Fd
		err = result.Values.Err
	}
	if result.DoReturnFn != nil {
		fd, err = result.DoReturnFn(domain, typ, proto)
	}
	return
}

func (m *MoqSocket_genType) OnCall(domain, typ, proto int) *MoqSocket_genType_fnRecorder {
	return &MoqSocket_genType_fnRecorder{
		Params: MoqSocket_genType_params{
			Domain: domain,
			Typ:    typ,
			Proto:  proto,
		},
		Sequence: m.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m,
	}
}

func (r *MoqSocket_genType_fnRecorder) Any() *MoqSocket_genType_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	return &MoqSocket_genType_anyParams{Recorder: r}
}

func (a *MoqSocket_genType_anyParams) Domain() *MoqSocket_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 0
	return a.Recorder
}

func (a *MoqSocket_genType_anyParams) Typ() *MoqSocket_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 1
	return a.Recorder
}

func (a *MoqSocket_genType_anyParams) Proto() *MoqSocket_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 2
	return a.Recorder
}

func (r *MoqSocket_genType_fnRecorder) Seq() *MoqSocket_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqSocket_genType_fnRecorder) NoSeq() *MoqSocket_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqSocket_genType_fnRecorder) ReturnResults(fd int, err error) *MoqSocket_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Fd  int
			Err error
		}
		Sequence   uint32
		DoFn       MoqSocket_genType_doFn
		DoReturnFn MoqSocket_genType_doReturnFn
	}{
		Values: &struct {
			Fd  int
			Err error
		}{
			Fd:  fd,
			Err: err,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqSocket_genType_fnRecorder) AndDo(fn MoqSocket_genType_doFn) *MoqSocket_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqSocket_genType_fnRecorder) DoReturnResults(fn MoqSocket_genType_doReturnFn) *MoqSocket_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Fd  int
			Err error
		}
		Sequence   uint32
		DoFn       MoqSocket_genType_doFn
		DoReturnFn MoqSocket_genType_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqSocket_genType_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqSocket_genType_resultsByParams
	for n, res := range r.Moq.ResultsByParams {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqSocket_genType_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqSocket_genType_paramsKey]*MoqSocket_genType_results{},
		}
		r.Moq.ResultsByParams = append(r.Moq.ResultsByParams, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams) {
			copy(r.Moq.ResultsByParams[insertAt+1:], r.Moq.ResultsByParams[insertAt:0])
			r.Moq.ResultsByParams[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqSocket_genType_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqSocket_genType_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqSocket_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Fd  int
					Err error
				}
				Sequence   uint32
				DoFn       MoqSocket_genType_doFn
				DoReturnFn MoqSocket_genType_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqSocket_genType) PrettyParams(params MoqSocket_genType_params) string {
	return fmt.Sprintf("Socket_genType(%#v, %#v, %#v)", params.Domain, params.Typ, params.Proto)
}

func (m *MoqSocket_genType) ParamsKey(params MoqSocket_genType_params, anyParams uint64) MoqSocket_genType_paramsKey {
	m.Scene.T.Helper()
	var domainUsed int
	var domainUsedHash hash.Hash
	if anyParams&(1<<0) == 0 {
		if m.Runtime.ParameterIndexing.Domain == moq.ParamIndexByValue {
			domainUsed = params.Domain
		} else {
			domainUsedHash = hash.DeepHash(params.Domain)
		}
	}
	var typUsed int
	var typUsedHash hash.Hash
	if anyParams&(1<<1) == 0 {
		if m.Runtime.ParameterIndexing.Typ == moq.ParamIndexByValue {
			typUsed = params.Typ
		} else {
			typUsedHash = hash.DeepHash(params.Typ)
		}
	}
	var protoUsed int
	var protoUsedHash hash.Hash
	if anyParams&(1<<2) == 0 {
		if m.Runtime.ParameterIndexing.Proto == moq.ParamIndexByValue {
			protoUsed = params.Proto
		} else {
			protoUsedHash = hash.DeepHash(params.Proto)
		}
	}
	return MoqSocket_genType_paramsKey{
		Params: struct{ Domain, Typ, Proto int }{
			Domain: domainUsed,
			Typ:    typUsed,
			Proto:  protoUsed,
		},
		Hashes: struct{ Domain, Typ, Proto hash.Hash }{
			Domain: domainUsedHash,
			Typ:    typUsedHash,
			Proto:  protoUsedHash,
		},
	}
}

// Reset resets the state of the moq
func (m *MoqSocket_genType) Reset() { m.ResultsByParams = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqSocket_genType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams(results.Params))
			}
		}
	}
}
