// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package types

import (
	"fmt"
	"go/types"
	"math/bits"
	"sync/atomic"

	"moqueries.org/runtime/hash"
	"moqueries.org/runtime/moq"
)

// NewUnion_genType is the fabricated implementation type of this mock (emitted
// when mocking functions directly and not from a function type)
type NewUnion_genType func(terms []*types.Term) *types.Union

// MoqNewUnion_genType holds the state of a moq of the NewUnion_genType type
type MoqNewUnion_genType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqNewUnion_genType_mock

	ResultsByParams []MoqNewUnion_genType_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			Terms moq.ParamIndexing
		}
	}
}

// MoqNewUnion_genType_mock isolates the mock interface of the NewUnion_genType
// type
type MoqNewUnion_genType_mock struct {
	Moq *MoqNewUnion_genType
}

// MoqNewUnion_genType_params holds the params of the NewUnion_genType type
type MoqNewUnion_genType_params struct{ Terms []*types.Term }

// MoqNewUnion_genType_paramsKey holds the map key params of the
// NewUnion_genType type
type MoqNewUnion_genType_paramsKey struct {
	Params struct{}
	Hashes struct{ Terms hash.Hash }
}

// MoqNewUnion_genType_resultsByParams contains the results for a given set of
// parameters for the NewUnion_genType type
type MoqNewUnion_genType_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqNewUnion_genType_paramsKey]*MoqNewUnion_genType_results
}

// MoqNewUnion_genType_doFn defines the type of function needed when calling
// AndDo for the NewUnion_genType type
type MoqNewUnion_genType_doFn func(terms []*types.Term)

// MoqNewUnion_genType_doReturnFn defines the type of function needed when
// calling DoReturnResults for the NewUnion_genType type
type MoqNewUnion_genType_doReturnFn func(terms []*types.Term) *types.Union

// MoqNewUnion_genType_results holds the results of the NewUnion_genType type
type MoqNewUnion_genType_results struct {
	Params  MoqNewUnion_genType_params
	Results []struct {
		Values *struct {
			Result1 *types.Union
		}
		Sequence   uint32
		DoFn       MoqNewUnion_genType_doFn
		DoReturnFn MoqNewUnion_genType_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqNewUnion_genType_fnRecorder routes recorded function calls to the
// MoqNewUnion_genType moq
type MoqNewUnion_genType_fnRecorder struct {
	Params    MoqNewUnion_genType_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqNewUnion_genType_results
	Moq       *MoqNewUnion_genType
}

// MoqNewUnion_genType_anyParams isolates the any params functions of the
// NewUnion_genType type
type MoqNewUnion_genType_anyParams struct {
	Recorder *MoqNewUnion_genType_fnRecorder
}

// NewMoqNewUnion_genType creates a new moq of the NewUnion_genType type
func NewMoqNewUnion_genType(scene *moq.Scene, config *moq.Config) *MoqNewUnion_genType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqNewUnion_genType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqNewUnion_genType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				Terms moq.ParamIndexing
			}
		}{ParameterIndexing: struct {
			Terms moq.ParamIndexing
		}{
			Terms: moq.ParamIndexByHash,
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the moq implementation of the NewUnion_genType type
func (m *MoqNewUnion_genType) Mock() NewUnion_genType {
	return func(terms []*types.Term) *types.Union {
		m.Scene.T.Helper()
		moq := &MoqNewUnion_genType_mock{Moq: m}
		return moq.Fn(terms)
	}
}

func (m *MoqNewUnion_genType_mock) Fn(terms []*types.Term) (result1 *types.Union) {
	m.Moq.Scene.T.Helper()
	params := MoqNewUnion_genType_params{
		Terms: terms,
	}
	var results *MoqNewUnion_genType_results
	for _, resultsByParams := range m.Moq.ResultsByParams {
		paramsKey := m.Moq.ParamsKey(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn(terms)
	}

	if result.Values != nil {
		result1 = result.Values.Result1
	}
	if result.DoReturnFn != nil {
		result1 = result.DoReturnFn(terms)
	}
	return
}

func (m *MoqNewUnion_genType) OnCall(terms []*types.Term) *MoqNewUnion_genType_fnRecorder {
	return &MoqNewUnion_genType_fnRecorder{
		Params: MoqNewUnion_genType_params{
			Terms: terms,
		},
		Sequence: m.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m,
	}
}

func (r *MoqNewUnion_genType_fnRecorder) Any() *MoqNewUnion_genType_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	return &MoqNewUnion_genType_anyParams{Recorder: r}
}

func (a *MoqNewUnion_genType_anyParams) Terms() *MoqNewUnion_genType_fnRecorder {
	a.Recorder.AnyParams |= 1 << 0
	return a.Recorder
}

func (r *MoqNewUnion_genType_fnRecorder) Seq() *MoqNewUnion_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqNewUnion_genType_fnRecorder) NoSeq() *MoqNewUnion_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqNewUnion_genType_fnRecorder) ReturnResults(result1 *types.Union) *MoqNewUnion_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 *types.Union
		}
		Sequence   uint32
		DoFn       MoqNewUnion_genType_doFn
		DoReturnFn MoqNewUnion_genType_doReturnFn
	}{
		Values: &struct {
			Result1 *types.Union
		}{
			Result1: result1,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqNewUnion_genType_fnRecorder) AndDo(fn MoqNewUnion_genType_doFn) *MoqNewUnion_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqNewUnion_genType_fnRecorder) DoReturnResults(fn MoqNewUnion_genType_doReturnFn) *MoqNewUnion_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 *types.Union
		}
		Sequence   uint32
		DoFn       MoqNewUnion_genType_doFn
		DoReturnFn MoqNewUnion_genType_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqNewUnion_genType_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqNewUnion_genType_resultsByParams
	for n, res := range r.Moq.ResultsByParams {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqNewUnion_genType_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqNewUnion_genType_paramsKey]*MoqNewUnion_genType_results{},
		}
		r.Moq.ResultsByParams = append(r.Moq.ResultsByParams, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams) {
			copy(r.Moq.ResultsByParams[insertAt+1:], r.Moq.ResultsByParams[insertAt:0])
			r.Moq.ResultsByParams[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqNewUnion_genType_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqNewUnion_genType_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqNewUnion_genType_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 *types.Union
				}
				Sequence   uint32
				DoFn       MoqNewUnion_genType_doFn
				DoReturnFn MoqNewUnion_genType_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqNewUnion_genType) PrettyParams(params MoqNewUnion_genType_params) string {
	return fmt.Sprintf("NewUnion_genType(%#v)", params.Terms)
}

func (m *MoqNewUnion_genType) ParamsKey(params MoqNewUnion_genType_params, anyParams uint64) MoqNewUnion_genType_paramsKey {
	m.Scene.T.Helper()
	var termsUsedHash hash.Hash
	if anyParams&(1<<0) == 0 {
		if m.Runtime.ParameterIndexing.Terms == moq.ParamIndexByValue {
			m.Scene.T.Fatalf("The terms parameter can't be indexed by value")
		}
		termsUsedHash = hash.DeepHash(params.Terms)
	}
	return MoqNewUnion_genType_paramsKey{
		Params: struct{}{},
		Hashes: struct{ Terms hash.Hash }{
			Terms: termsUsedHash,
		},
	}
}

// Reset resets the state of the moq
func (m *MoqNewUnion_genType) Reset() { m.ResultsByParams = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqNewUnion_genType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams(results.Params))
			}
		}
	}
}
