// Code generated by Moqueries - https://moqueries.org - DO NOT EDIT!

package user

import (
	"fmt"
	"math/bits"
	"sync/atomic"

	"moqueries.org/runtime/moq"
)

// The following type assertion assures that user.User_starGenType is mocked
// completely
var _ User_starGenType = (*MoqUser_starGenType_mock)(nil)

// User_starGenType is the fabricated implementation type of this mock (emitted
// when mocking a collections of methods directly and not from an interface
// type)
type User_starGenType interface {
	GroupIds() ([]string, error)
}

// MoqUser_starGenType holds the state of a moq of the User_starGenType type
type MoqUser_starGenType struct {
	Scene  *moq.Scene
	Config moq.Config
	Moq    *MoqUser_starGenType_mock

	ResultsByParams_GroupIds []MoqUser_starGenType_GroupIds_resultsByParams

	Runtime struct {
		ParameterIndexing struct {
			GroupIds struct{}
		}
	}
}

// MoqUser_starGenType_mock isolates the mock interface of the User_starGenType
// type
type MoqUser_starGenType_mock struct {
	Moq *MoqUser_starGenType
}

// MoqUser_starGenType_recorder isolates the recorder interface of the
// User_starGenType type
type MoqUser_starGenType_recorder struct {
	Moq *MoqUser_starGenType
}

// MoqUser_starGenType_GroupIds_params holds the params of the User_starGenType
// type
type MoqUser_starGenType_GroupIds_params struct{}

// MoqUser_starGenType_GroupIds_paramsKey holds the map key params of the
// User_starGenType type
type MoqUser_starGenType_GroupIds_paramsKey struct {
	Params struct{}
	Hashes struct{}
}

// MoqUser_starGenType_GroupIds_resultsByParams contains the results for a
// given set of parameters for the User_starGenType type
type MoqUser_starGenType_GroupIds_resultsByParams struct {
	AnyCount  int
	AnyParams uint64
	Results   map[MoqUser_starGenType_GroupIds_paramsKey]*MoqUser_starGenType_GroupIds_results
}

// MoqUser_starGenType_GroupIds_doFn defines the type of function needed when
// calling AndDo for the User_starGenType type
type MoqUser_starGenType_GroupIds_doFn func()

// MoqUser_starGenType_GroupIds_doReturnFn defines the type of function needed
// when calling DoReturnResults for the User_starGenType type
type MoqUser_starGenType_GroupIds_doReturnFn func() ([]string, error)

// MoqUser_starGenType_GroupIds_results holds the results of the
// User_starGenType type
type MoqUser_starGenType_GroupIds_results struct {
	Params  MoqUser_starGenType_GroupIds_params
	Results []struct {
		Values *struct {
			Result1 []string
			Result2 error
		}
		Sequence   uint32
		DoFn       MoqUser_starGenType_GroupIds_doFn
		DoReturnFn MoqUser_starGenType_GroupIds_doReturnFn
	}
	Index  uint32
	Repeat *moq.RepeatVal
}

// MoqUser_starGenType_GroupIds_fnRecorder routes recorded function calls to
// the MoqUser_starGenType moq
type MoqUser_starGenType_GroupIds_fnRecorder struct {
	Params    MoqUser_starGenType_GroupIds_params
	AnyParams uint64
	Sequence  bool
	Results   *MoqUser_starGenType_GroupIds_results
	Moq       *MoqUser_starGenType
}

// MoqUser_starGenType_GroupIds_anyParams isolates the any params functions of
// the User_starGenType type
type MoqUser_starGenType_GroupIds_anyParams struct {
	Recorder *MoqUser_starGenType_GroupIds_fnRecorder
}

// NewMoqUser_starGenType creates a new moq of the User_starGenType type
func NewMoqUser_starGenType(scene *moq.Scene, config *moq.Config) *MoqUser_starGenType {
	if config == nil {
		config = &moq.Config{}
	}
	m := &MoqUser_starGenType{
		Scene:  scene,
		Config: *config,
		Moq:    &MoqUser_starGenType_mock{},

		Runtime: struct {
			ParameterIndexing struct {
				GroupIds struct{}
			}
		}{ParameterIndexing: struct {
			GroupIds struct{}
		}{
			GroupIds: struct{}{},
		}},
	}
	m.Moq.Moq = m

	scene.AddMoq(m)
	return m
}

// Mock returns the mock implementation of the User_starGenType type
func (m *MoqUser_starGenType) Mock() *MoqUser_starGenType_mock { return m.Moq }

func (m *MoqUser_starGenType_mock) GroupIds() (result1 []string, result2 error) {
	m.Moq.Scene.T.Helper()
	params := MoqUser_starGenType_GroupIds_params{}
	var results *MoqUser_starGenType_GroupIds_results
	for _, resultsByParams := range m.Moq.ResultsByParams_GroupIds {
		paramsKey := m.Moq.ParamsKey_GroupIds(params, resultsByParams.AnyParams)
		var ok bool
		results, ok = resultsByParams.Results[paramsKey]
		if ok {
			break
		}
	}
	if results == nil {
		if m.Moq.Config.Expectation == moq.Strict {
			m.Moq.Scene.T.Fatalf("Unexpected call to %s", m.Moq.PrettyParams_GroupIds(params))
		}
		return
	}

	i := int(atomic.AddUint32(&results.Index, 1)) - 1
	if i >= results.Repeat.ResultCount {
		if !results.Repeat.AnyTimes {
			if m.Moq.Config.Expectation == moq.Strict {
				m.Moq.Scene.T.Fatalf("Too many calls to %s", m.Moq.PrettyParams_GroupIds(params))
			}
			return
		}
		i = results.Repeat.ResultCount - 1
	}

	result := results.Results[i]
	if result.Sequence != 0 {
		sequence := m.Moq.Scene.NextMockSequence()
		if (!results.Repeat.AnyTimes && result.Sequence != sequence) || result.Sequence > sequence {
			m.Moq.Scene.T.Fatalf("Call sequence does not match call to %s", m.Moq.PrettyParams_GroupIds(params))
		}
	}

	if result.DoFn != nil {
		result.DoFn()
	}

	if result.Values != nil {
		result1 = result.Values.Result1
		result2 = result.Values.Result2
	}
	if result.DoReturnFn != nil {
		result1, result2 = result.DoReturnFn()
	}
	return
}

// OnCall returns the recorder implementation of the User_starGenType type
func (m *MoqUser_starGenType) OnCall() *MoqUser_starGenType_recorder {
	return &MoqUser_starGenType_recorder{
		Moq: m,
	}
}

func (m *MoqUser_starGenType_recorder) GroupIds() *MoqUser_starGenType_GroupIds_fnRecorder {
	return &MoqUser_starGenType_GroupIds_fnRecorder{
		Params:   MoqUser_starGenType_GroupIds_params{},
		Sequence: m.Moq.Config.Sequence == moq.SeqDefaultOn,
		Moq:      m.Moq,
	}
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) Any() *MoqUser_starGenType_GroupIds_anyParams {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Any functions must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_GroupIds(r.Params))
		return nil
	}
	return &MoqUser_starGenType_GroupIds_anyParams{Recorder: r}
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) Seq() *MoqUser_starGenType_GroupIds_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("Seq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_GroupIds(r.Params))
		return nil
	}
	r.Sequence = true
	return r
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) NoSeq() *MoqUser_starGenType_GroupIds_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Moq.Scene.T.Fatalf("NoSeq must be called before ReturnResults or DoReturnResults calls, recording %s", r.Moq.PrettyParams_GroupIds(r.Params))
		return nil
	}
	r.Sequence = false
	return r
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) ReturnResults(result1 []string, result2 error) *MoqUser_starGenType_GroupIds_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 []string
			Result2 error
		}
		Sequence   uint32
		DoFn       MoqUser_starGenType_GroupIds_doFn
		DoReturnFn MoqUser_starGenType_GroupIds_doReturnFn
	}{
		Values: &struct {
			Result1 []string
			Result2 error
		}{
			Result1: result1,
			Result2: result2,
		},
		Sequence: sequence,
	})
	return r
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) AndDo(fn MoqUser_starGenType_GroupIds_doFn) *MoqUser_starGenType_GroupIds_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults must be called before calling AndDo")
		return nil
	}
	last := &r.Results.Results[len(r.Results.Results)-1]
	last.DoFn = fn
	return r
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) DoReturnResults(fn MoqUser_starGenType_GroupIds_doReturnFn) *MoqUser_starGenType_GroupIds_fnRecorder {
	r.Moq.Scene.T.Helper()
	r.FindResults()

	var sequence uint32
	if r.Sequence {
		sequence = r.Moq.Scene.NextRecorderSequence()
	}

	r.Results.Results = append(r.Results.Results, struct {
		Values *struct {
			Result1 []string
			Result2 error
		}
		Sequence   uint32
		DoFn       MoqUser_starGenType_GroupIds_doFn
		DoReturnFn MoqUser_starGenType_GroupIds_doReturnFn
	}{Sequence: sequence, DoReturnFn: fn})
	return r
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) FindResults() {
	r.Moq.Scene.T.Helper()
	if r.Results != nil {
		r.Results.Repeat.Increment(r.Moq.Scene.T)
		return
	}

	anyCount := bits.OnesCount64(r.AnyParams)
	insertAt := -1
	var results *MoqUser_starGenType_GroupIds_resultsByParams
	for n, res := range r.Moq.ResultsByParams_GroupIds {
		if res.AnyParams == r.AnyParams {
			results = &res
			break
		}
		if res.AnyCount > anyCount {
			insertAt = n
		}
	}
	if results == nil {
		results = &MoqUser_starGenType_GroupIds_resultsByParams{
			AnyCount:  anyCount,
			AnyParams: r.AnyParams,
			Results:   map[MoqUser_starGenType_GroupIds_paramsKey]*MoqUser_starGenType_GroupIds_results{},
		}
		r.Moq.ResultsByParams_GroupIds = append(r.Moq.ResultsByParams_GroupIds, *results)
		if insertAt != -1 && insertAt+1 < len(r.Moq.ResultsByParams_GroupIds) {
			copy(r.Moq.ResultsByParams_GroupIds[insertAt+1:], r.Moq.ResultsByParams_GroupIds[insertAt:0])
			r.Moq.ResultsByParams_GroupIds[insertAt] = *results
		}
	}

	paramsKey := r.Moq.ParamsKey_GroupIds(r.Params, r.AnyParams)

	var ok bool
	r.Results, ok = results.Results[paramsKey]
	if !ok {
		r.Results = &MoqUser_starGenType_GroupIds_results{
			Params:  r.Params,
			Results: nil,
			Index:   0,
			Repeat:  &moq.RepeatVal{},
		}
		results.Results[paramsKey] = r.Results
	}

	r.Results.Repeat.Increment(r.Moq.Scene.T)
}

func (r *MoqUser_starGenType_GroupIds_fnRecorder) Repeat(repeaters ...moq.Repeater) *MoqUser_starGenType_GroupIds_fnRecorder {
	r.Moq.Scene.T.Helper()
	if r.Results == nil {
		r.Moq.Scene.T.Fatalf("ReturnResults or DoReturnResults must be called before calling Repeat")
		return nil
	}
	r.Results.Repeat.Repeat(r.Moq.Scene.T, repeaters)
	last := r.Results.Results[len(r.Results.Results)-1]
	for n := 0; n < r.Results.Repeat.ResultCount-1; n++ {
		if r.Sequence {
			last = struct {
				Values *struct {
					Result1 []string
					Result2 error
				}
				Sequence   uint32
				DoFn       MoqUser_starGenType_GroupIds_doFn
				DoReturnFn MoqUser_starGenType_GroupIds_doReturnFn
			}{
				Values:   last.Values,
				Sequence: r.Moq.Scene.NextRecorderSequence(),
			}
		}
		r.Results.Results = append(r.Results.Results, last)
	}
	return r
}

func (m *MoqUser_starGenType) PrettyParams_GroupIds(params MoqUser_starGenType_GroupIds_params) string {
	return fmt.Sprintf("GroupIds()")
}

func (m *MoqUser_starGenType) ParamsKey_GroupIds(params MoqUser_starGenType_GroupIds_params, anyParams uint64) MoqUser_starGenType_GroupIds_paramsKey {
	m.Scene.T.Helper()
	return MoqUser_starGenType_GroupIds_paramsKey{
		Params: struct{}{},
		Hashes: struct{}{},
	}
}

// Reset resets the state of the moq
func (m *MoqUser_starGenType) Reset() { m.ResultsByParams_GroupIds = nil }

// AssertExpectationsMet asserts that all expectations have been met
func (m *MoqUser_starGenType) AssertExpectationsMet() {
	m.Scene.T.Helper()
	for _, res := range m.ResultsByParams_GroupIds {
		for _, results := range res.Results {
			missing := results.Repeat.MinTimes - int(atomic.LoadUint32(&results.Index))
			if missing > 0 {
				m.Scene.T.Errorf("Expected %d additional call(s) to %s", missing, m.PrettyParams_GroupIds(results.Params))
			}
		}
	}
}
